# Generated by Django 5.0.4 on 2024-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=60),
        ),
    ]
