# Generated by Django 5.0.4 on 2024-06-30 09:37

import actors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=actors.models.upload_to),
        ),
    ]
